// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJiYjTv5Sc_oeAHLYodXCCQmDMq1mIcWk',
    appId: '1:892035394944:web:e6853b7bd0fdf8cacbe565',
    messagingSenderId: '892035394944',
    projectId: 'mynotes-a195d',
    authDomain: 'mynotes-a195d.firebaseapp.com',
    storageBucket: 'mynotes-a195d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwxhwAOvZckGD1QI6aFIcdrRgOLqWrCj4',
    appId: '1:892035394944:android:5fe7f6971f98cefecbe565',
    messagingSenderId: '892035394944',
    projectId: 'mynotes-a195d',
    storageBucket: 'mynotes-a195d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDodDldU2-ErtHyOyb06HTJGLy7U67o9Qo',
    appId: '1:892035394944:ios:d64958e57fa596ebcbe565',
    messagingSenderId: '892035394944',
    projectId: 'mynotes-a195d',
    storageBucket: 'mynotes-a195d.appspot.com',
    iosClientId: '892035394944-dhmihjhih3l82avq9gv3vv001bci46f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDodDldU2-ErtHyOyb06HTJGLy7U67o9Qo',
    appId: '1:892035394944:ios:d64958e57fa596ebcbe565',
    messagingSenderId: '892035394944',
    projectId: 'mynotes-a195d',
    storageBucket: 'mynotes-a195d.appspot.com',
    iosClientId: '892035394944-dhmihjhih3l82avq9gv3vv001bci46f6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLearning',
  );
}
